EXPERIMENT:
  NAME: ""
  TAG: "fed_VPTRes50_VPTRes18"
  PROJECT: "iid_fed_train"
DISTILLER:
  TYPE: "KD_ours"
  TEACHER: "ResNet50"
  STUDENT: "resnet110"
FEDERATED:
  CLIENT: "VPTResNet18"
  SERVER: "VPTResNet50"
  ROUND: 10
  CLIENT_NUM: 4
  N_SHOT: 50
  LOCAL_EPOCH: 5
  CLIENT_SHOTS: [50,50,50,50]
  UNLEARNING_CLIENT: [0,1]
  RECOVER_R: 3
  BACKDOOR: True
  POISON_RATIO: 0.6
DATASET:
  TYPE: "breakhis"
  NUM_WORKERS: 4
  TEST:
    BATCH_SIZE: 32
SOLVER:
  BATCH_SIZE: 1
  EPOCHS: 1
  LR: 0.01
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"
  TRAINER: "ours"
