EXPERIMENT:
  NAME: ""
  TAG: "fed_VPTRes152_VPTRes18"
  PROJECT: "fed_train"
DISTILLER:
  TYPE: "KD_ours"
  TEACHER: "ResNet50"
  STUDENT: "resnet110"
FEDERATED:
  CLIENT: "VPTResNet18"
  SERVER: "VPTResNet152"
  ROUND: 20
  CLIENT_NUM: 5
  N_SHOT: 50
  LOCAL_EPOCH: 10
DATASET:
  TYPE: "tinyimagenet"
  NUM_WORKERS: 6
  TEST:
    BATCH_SIZE: 32
SOLVER:
  BATCH_SIZE: 32
  EPOCHS: 10
  LR: 0.001
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"
  TRAINER: "ours"
