EXPERIMENT:
  NAME: ""
  TAG: "fed_VPTRes101_VPTRes18"
  PROJECT: "iid_fed_train"
DISTILLER:
  TYPE: "KD_ours"
  TEACHER: "ResNet50"
  STUDENT: "resnet110"
FEDERATED:
  CLIENT: "VPTResNet18"
  SERVER: "VPTResNet101"
  ROUND: 20
  CLIENT_NUM: 5
  N_SHOT: 50
  LOCAL_EPOCH: 10
  CLIENT_SHOTS: [6,6,6,6,6]
  CLIENT_LR: 0.00015

DATASET:
  TYPE: "oxford_flowers"
  NUM_WORKERS: 6
  TEST:
    BATCH_SIZE: 64
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 10
  LR: 0.001
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"
  TRAINER: "ours"
