EXPERIMENT:
  NAME: ""
  TAG: "ds_fed_VPTRes101_VPTRes18_10C"
  PROJECT: "non_iid_fed_train_10C"
DISTILLER:
  TYPE: "KD_ours"
  TEACHER: "ResNet50"
  STUDENT: "resnet110"
FEDERATED:
  CLIENT: "VPTResNet18"
  SERVER: "VPTResNet101"
  ROUND: 10
  CLIENT_NUM: 10
  N_SHOT: 50
  LOCAL_EPOCH: 5
  CLIENT_SHOTS: [1,2,4,8,16,16,32,32,64,64]
  UNLEARNING_CLIENT: [0,1,2,3,4,5]
  RECOVER_R: 3
  BACKDOOR: False
  POISON_RATIO: 0.6
DATASET:
  TYPE: "tinyimagenet"
  NUM_WORKERS: 6
  TEST:
    BATCH_SIZE: 32
SOLVER:
  BATCH_SIZE: 2
  EPOCHS: 1
  LR: 0.08
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"
  TRAINER: "ours"
